// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"QunDev/GoRemoteDesktop_Server/internal/websocket"
	"QunDev/GoRemoteDesktop_Server/pkg/config"
	"QunDev/GoRemoteDesktop_Server/pkg/logger"
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	contextContext := context.Background()
	hub := websocket.NewHub()
	app := NewApp(configConfig, loggerLogger, contextContext, hub)
	return app, nil
}

// wire.go:

var ContextSet = wire.NewSet(context.Background)

var ConfigSet = wire.NewSet(config.NewConfig)

var LoggerSet = wire.NewSet(logger.NewLogger)

var SocketServerSet = wire.NewSet(websocket.NewHub)

var AppSet = wire.NewSet(
	NewApp,
)
